import { z } from 'zod';

import {
  actionStatuses,
  aiStatuses,
  approvalStates,
  clientStatuses,
  confidenceLevels,
  engagementTypes,
  evidenceReviewStatuses,
  evidenceTypes,
  diagnosticStatuses,
  benefitMeasures,
  benefitValidationStatuses,
  investmentBands,
  landscapeEntityTypes,
  landscapeRelationshipTypes,
  maturityLevels,
  opportunityPriorityCategories,
  reviewStatuses,
  effortLevels,
  engagementStatuses,
  evidenceKinds,
  informationOrigins,
  initiativeStatuses,
  observationAssuranceLevels,
  observationSources,
  observationStatuses,
  observationTypes,
  opportunityPriorities,
  opportunityStatuses,
  opportunityTypes,
  outputKinds,
  outputStates,
  relatedEntityTypes,
  siteWalkStatuses,
  siteWalkTypes,
  siteStatuses,
  frictionCategories,
  transformationStages,
  userRoles,
  visibilityScopes,
} from '@domain';

const isoDateTimeSchema = z.string().datetime({ offset: true });

const baseEntitySchema = z.object({
  id: z.string().min(1),
  createdAt: isoDateTimeSchema,
  updatedAt: isoDateTimeSchema,
});

export const userSchema = baseEntitySchema.extend({
  displayName: z.string().min(1),
  role: z.enum(userRoles),
  email: z.string().email(),
});

export const clientSchema = baseEntitySchema.extend({
  name: z.string().min(1),
  slug: z.string().min(1),
  industry: z.string().min(1),
  companySize: z.string().min(1).optional(),
  description: z.string().min(1).optional(),
  status: z.enum(clientStatuses),
  primaryContact: z.string().min(1).optional(),
  contactDetails: z.string().min(1).optional(),
  notes: z.string().min(1).optional(),
});

export const siteSchema = baseEntitySchema.extend({
  clientId: z.string().min(1),
  name: z.string().min(1),
  location: z.string().min(1),
  description: z.string().min(1),
  operationalProfile: z.string().min(1),
  siteType: z.string().min(1).optional(),
  workforce: z.string().min(1).optional(),
  shifts: z.string().min(1).optional(),
  status: z.enum(siteStatuses).optional(),
  internalNotes: z.string().min(1).optional(),
  areaIds: z.array(z.string().min(1)),
  systemIds: z.array(z.string().min(1)),
});

export const areaSchema = baseEntitySchema.extend({
  siteId: z.string().min(1),
  name: z.string().min(1),
  description: z.string().min(1),
});

export const processSchema = baseEntitySchema.extend({
  siteId: z.string().min(1),
  areaId: z.string().min(1),
  name: z.string().min(1),
  description: z.string().min(1),
  relatedSystemIds: z.array(z.string().min(1)),
});

export const operationalSystemSchema = baseEntitySchema.extend({
  siteId: z.string().min(1),
  name: z.string().min(1),
  category: z.string().min(1),
  description: z.string().min(1),
  ownerTeam: z.string().min(1),
});

export const engagementSchema = baseEntitySchema.extend({
  clientId: z.string().min(1),
  siteIds: z.array(z.string().min(1)).min(1),
  name: z.string().min(1),
  description: z.string().min(1),
  type: z.enum(engagementTypes),
  objectives: z.string().min(1).optional(),
  scope: z.string().min(1).optional(),
  commercialContext: z.string().min(1).optional(),
  internalNotes: z.string().min(1).optional(),
  status: z.enum(engagementStatuses),
  stage: z.enum(transformationStages),
  startDate: isoDateTimeSchema,
  targetDate: isoDateTimeSchema.optional(),
  leadUserId: z.string().min(1),
  teamUserIds: z.array(z.string().min(1)).min(1),
});

export const siteWalkSchema = baseEntitySchema.extend({
  engagementId: z.string().min(1),
  siteId: z.string().min(1),
  areaId: z.string().min(1).optional(),
  processId: z.string().min(1).optional(),
  title: z.string().min(1),
  scheduledAt: isoDateTimeSchema,
  consultantUserId: z.string().min(1),
  walkType: z.union([z.enum(siteWalkTypes), z.string().min(1)]),
  plannedScope: z.array(z.string().min(1)).min(1),
  completedScope: z.array(z.string().min(1)),
  status: z.enum(siteWalkStatuses),
  followUpActionIds: z.array(z.string().min(1)),
  date: z.string().optional(),
  startTime: z.string().optional(),
  endTime: z.string().optional(),
  leadConsultantId: z.string().min(1).optional(),
  participantUserIds: z.array(z.string().min(1)).optional(),
  participants: z.string().min(1).optional(),
  objectives: z.string().min(1).optional(),
  businessContext: z.string().min(1).optional(),
  focusAreas: z.array(z.string().min(1)).optional(),
  areasCovered: z.array(z.string().min(1)).optional(),
  processesCovered: z.array(z.string().min(1)).optional(),
  overallProcessSummary: z.string().min(1).optional(),
  candidateBottleneck: z.string().min(1).optional(),
  agreedNextStep: z.string().min(1).optional(),
  internalNotes: z.string().min(1).optional(),
  briefingChecklist: z.record(z.boolean()).optional(),
  postTourNotes: z.string().min(1).optional(),
  validationNotes: z.string().min(1).optional(),
  confirmedBottleneck: z.string().min(1).optional(),
  correctedMisunderstandings: z.string().min(1).optional(),
  immediateOpportunities: z.string().min(1).optional(),
  recommendDiagnostic: z.boolean().optional(),
  followUpOwnerId: z.string().min(1).optional(),
  followUpDate: z.string().optional(),
});

export const observationSchema = baseEntitySchema.extend({
  siteWalkId: z.string().min(1),
  processId: z.string().min(1).optional(),
  summary: z.string().min(1),
  detail: z.string().min(1),
  observedAt: isoDateTimeSchema,
  origin: z.enum(informationOrigins),
  assurance: z.enum(observationAssuranceLevels),
  visibility: z.enum(visibilityScopes),
  aiStatus: z.enum(aiStatuses),
  evidenceIds: z.array(z.string().min(1)),
  title: z.string().min(1).optional(),
  description: z.string().min(1).optional(),
  observationType: z.enum(observationTypes).optional(),
  areaId: z.string().min(1).optional(),
  systemId: z.string().min(1).optional(),
  stationOrLine: z.string().min(1).optional(),
  source: z.enum(observationSources).optional(),
  confidence: z.enum(confidenceLevels).optional(),
  status: z.enum(observationStatuses).optional(),
  recordedByUserId: z.string().min(1).optional(),
  internalNotes: z.string().min(1).optional(),
});

export const evidenceSchema = baseEntitySchema.extend({
  relatedEntityId: z.string().min(1),
  relatedEntityType: z.enum(relatedEntityTypes),
  kind: z.enum(evidenceKinds),
  title: z.string().min(1),
  summary: z.string().min(1),
  capturedAt: isoDateTimeSchema,
  origin: z.enum(informationOrigins),
  visibility: z.enum(visibilityScopes),
  approvalState: z.enum(approvalStates),
  observationId: z.string().min(1).optional(),
  siteWalkId: z.string().min(1).optional(),
  evidenceType: z.enum(evidenceTypes).optional(),
  description: z.string().min(1).optional(),
  fileReference: z.string().min(1).optional(),
  source: z.enum(observationSources).optional(),
  capturedByUserId: z.string().min(1).optional(),
  reviewStatus: z.enum(evidenceReviewStatuses).optional(),
});

export const frictionItemSchema = baseEntitySchema.extend({
  siteWalkId: z.string().min(1),
  stationOrLine: z.string().min(1),
  frictionPoint: z.string().min(1),
  category: z.enum(frictionCategories),
  estimatedTimeLost: z.string().min(1).optional(),
  frequency: z.string().min(1).optional(),
  peopleOrShiftsAffected: z.string().min(1).optional(),
  estimatedAnnualHours: z.number().nonnegative().optional(),
  estimatedAnnualCostImpact: z.string().min(1).optional(),
  confidence: z.enum(confidenceLevels),
  evidenceReference: z.string().min(1).optional(),
  assumptions: z.string().min(1).optional(),
  notes: z.string().min(1).optional(),
});

export const diagnosticDimensionSchema = baseEntitySchema.extend({
  key: z.string().min(1),
  name: z.string().min(1),
  version: z.string().min(1),
  description: z.string().min(1),
  criteria: z.array(z.string().min(1)).min(1),
  anchors: z.record(z.string()),
});

export const diagnosticSchema = baseEntitySchema.extend({
  engagementId: z.string().min(1),
  title: z.string().min(1),
  description: z.string().min(1),
  status: z.enum(diagnosticStatuses),
  startDate: isoDateTimeSchema,
  completionDate: isoDateTimeSchema.optional(),
  assessorUserId: z.string().min(1),
  currentStage: z.enum(transformationStages),
  scope: z.string().min(1),
  methodologyVersion: z.string().min(1),
  overallScore: z.number().min(1).max(5).optional(),
  overallLevel: z.enum(maturityLevels).optional(),
  overallConfidence: z.enum(confidenceLevels).optional(),
  internalNotes: z.string().min(1).optional(),
});

export const maturityAssessmentSchema = baseEntitySchema.extend({
  diagnosticId: z.string().min(1),
  dimensionId: z.string().min(1),
  score: z.number().min(1).max(5).optional(),
  level: z.enum(maturityLevels).optional(),
  rationale: z.string().min(1).optional(),
  currentState: z.string().min(1).optional(),
  desiredState: z.string().min(1).optional(),
  gap: z.string().min(1).optional(),
  relatedObservationIds: z.array(z.string().min(1)),
  evidenceReferences: z.array(z.string().min(1)),
  relatedOpportunityIds: z.array(z.string().min(1)),
  confidence: z.enum(confidenceLevels),
  reviewStatus: z.enum(reviewStatuses),
  assessedByUserId: z.string().min(1).optional(),
  assessedAt: isoDateTimeSchema.optional(),
}).superRefine((assessment, context) => {
  if (assessment.score !== undefined && !assessment.rationale) {
    context.addIssue({ code: z.ZodIssueCode.custom, path: ['rationale'], message: 'A scored dimension requires rationale.' });
  }
});

export const findingSchema = baseEntitySchema.extend({
  diagnosticId: z.string().min(1),
  title: z.string().min(1),
  currentSituation: z.string().min(1),
  whyItMatters: z.string().min(1),
  recommendedDirection: z.string().min(1),
  category: z.string().min(1),
  significance: z.enum(opportunityPriorities),
  relatedObservationIds: z.array(z.string().min(1)),
  relatedEvidenceIds: z.array(z.string().min(1)),
  relatedOpportunityIds: z.array(z.string().min(1)),
  confidence: z.enum(confidenceLevels),
  reviewStatus: z.enum(reviewStatuses),
  internalNotes: z.string().min(1).optional(),
  clientSummary: z.string().min(1).optional(),
});

export const landscapeEntitySchema = baseEntitySchema.extend({
  engagementId: z.string().min(1),
  type: z.enum(landscapeEntityTypes),
  name: z.string().min(1),
  description: z.string().min(1),
  sourceEntityId: z.string().min(1).optional(),
  ownerRole: z.string().min(1).optional(),
});

export const landscapeRelationshipSchema = baseEntitySchema.extend({
  engagementId: z.string().min(1),
  fromEntityId: z.string().min(1),
  toEntityId: z.string().min(1),
  type: z.enum(landscapeRelationshipTypes),
  rationale: z.string().min(1).optional(),
  evidenceIds: z.array(z.string().min(1)),
});

export const opportunitySchema = baseEntitySchema.extend({
  engagementId: z.string().min(1),
  processId: z.string().min(1).optional(),
  areaId: z.string().min(1).optional(),
  title: z.string().min(1),
  description: z.string().min(1),
  problemStatement: z.string().min(1),
  rootCause: z.string().min(1),
  type: z.enum(opportunityTypes),
  expectedImpact: z.string().min(1),
  estimatedValueRange: z.string().min(1).optional(),
  estimatedEffort: z.enum(effortLevels),
  confidence: z.enum(confidenceLevels),
  priority: z.enum(opportunityPriorities),
  status: z.enum(opportunityStatuses),
  ownerUserId: z.string().min(1).optional(),
  evidenceIds: z.array(z.string().min(1)),
  internalNotes: z.string().min(1).optional(),
  clientSummary: z.string().min(1).optional(),
  approvalState: z.enum(approvalStates),
  initiativeIds: z.array(z.string().min(1)),
  diagnosticId: z.string().min(1).optional(),
  systemId: z.string().min(1).optional(),
  currentSituation: z.string().min(1).optional(),
  identifiedIssue: z.string().min(1).optional(),
  whyItMatters: z.string().min(1).optional(),
  recommendedImprovement: z.string().min(1).optional(),
  potentialBenefits: z.string().min(1).optional(),
  indicativeValue: z.string().min(1).optional(),
  valueAssumptions: z.string().min(1).optional(),
  businessImpact: z.enum(opportunityPriorities).optional(),
  implementationEffort: z.enum(effortLevels).optional(),
  investment: z.enum(investmentBands).optional(),
  strategicValue: z.enum(opportunityPriorities).optional(),
  priorityCategory: z.enum(opportunityPriorityCategories).optional(),
  recommendedTiming: z.string().min(1).optional(),
  dependencies: z.string().min(1).optional(),
  suggestedNextStep: z.string().min(1).optional(),
  relatedObservationIds: z.array(z.string().min(1)).optional(),
  relatedFindingIds: z.array(z.string().min(1)).optional(),
  evidenceReferences: z.array(z.string().min(1)).optional(),
  owner: z.string().min(1).optional(),
  reviewStatus: z.enum(reviewStatuses).optional(),
  benefitMeasures: z.array(z.object({
    id: z.string().min(1),
    createdAt: isoDateTimeSchema,
    updatedAt: isoDateTimeSchema,
    opportunityId: z.string().min(1),
    measure: z.enum(benefitMeasures),
    currentState: z.string().min(1),
    potentialState: z.string().min(1),
    unit: z.string().min(1),
    calculationOrAssumption: z.string().min(1),
    confidence: z.enum(confidenceLevels),
    validationStatus: z.enum(benefitValidationStatuses),
  })).optional(),
});

export const actionItemSchema = baseEntitySchema.extend({
  initiativeId: z.string().min(1).optional(),
  opportunityId: z.string().min(1).optional(),
  title: z.string().min(1),
  description: z.string().min(1),
  status: z.enum(actionStatuses),
  ownerUserId: z.string().min(1).optional(),
  dueDate: isoDateTimeSchema.optional(),
  priority: z.enum(opportunityPriorities).optional(),
  dependencies: z.string().min(1).optional(),
  notes: z.string().min(1).optional(),
  owner: z.string().min(1).optional(),
});

export const initiativeSchema = baseEntitySchema.extend({
  engagementId: z.string().min(1),
  opportunityIds: z.array(z.string().min(1)).min(1),
  title: z.string().min(1),
  summary: z.string().min(1),
  status: z.enum(initiativeStatuses),
  ownerUserId: z.string().min(1),
  targetWindow: z.string().min(1),
  expectedBenefits: z.string().min(1),
  actualBenefits: z.string().min(1).optional(),
  actionIds: z.array(z.string().min(1)),
});

export const outputSchema = baseEntitySchema.extend({
  engagementId: z.string().min(1),
  kind: z.enum(outputKinds),
  title: z.string().min(1),
  state: z.enum(outputStates),
  visibility: z.enum(visibilityScopes),
  approvedEntityIds: z.array(z.string().min(1)),
  lastPublishedAt: isoDateTimeSchema.optional(),
});

export const fabricDatasetSchema = z.object({
  users: z.array(userSchema),
  clients: z.array(clientSchema),
  sites: z.array(siteSchema),
  areas: z.array(areaSchema),
  processes: z.array(processSchema),
  systems: z.array(operationalSystemSchema),
  engagements: z.array(engagementSchema),
  siteWalks: z.array(siteWalkSchema),
  observations: z.array(observationSchema),
  evidence: z.array(evidenceSchema),
  frictionItems: z.array(frictionItemSchema).default([]),
  diagnosticDimensions: z.array(diagnosticDimensionSchema).default([]),
  diagnostics: z.array(diagnosticSchema).default([]),
  maturityAssessments: z.array(maturityAssessmentSchema).default([]),
  findings: z.array(findingSchema).default([]),
  landscapeEntities: z.array(landscapeEntitySchema).default([]),
  landscapeRelationships: z.array(landscapeRelationshipSchema).default([]),
  opportunities: z.array(opportunitySchema),
  actionItems: z.array(actionItemSchema),
  initiatives: z.array(initiativeSchema),
  outputs: z.array(outputSchema),
});